from app.prompts.medical_prompts import (
    SYMPTOM_ANALYSIS_SYSTEM_PROMPT,
    SYMPTOM_ANALYSIS_HUMAN_PROMPT,
    URGENCY_CLASSIFIER_SYSTEM_PROMPT,
    URGENCY_CLASSIFIER_HUMAN_PROMPT,
    GUARDRAIL_SYSTEM_PROMPT,
    GUARDRAIL_HUMAN_PROMPT,
    MEDICAL_DISCLAIMER,
    EMERGENCY_DISCLAIMER
)